version: '3'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile-backend
    ports:
      - "8080:8080"
    networks:
      - mynetwork
    depends_on:
      - database

  database:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=PSdata
    ports:
      - "5432:5432"
    networks:
      - mynetwork

  frontend:
    build:
      context: .
      dockerfile: Dockerfile-frontend
    ports:
      - "80:80"
    networks:
      - mynetwork

networks:
  mynetwork: