FROM maven:latest
COPY . /app
WORKDIR /app
RUN mvn clean install -DskipTests
CMD ["java", "-jar", "target/ProjectSupport-0.0.1-SNAPSHOT.jar", "--spring.config.location=src/main/resources/application-docker.properties"]